import Player from "./types/players";
import Table, {
  PokerVariants,
  Value,
  Suit,
  BetActionType,
} from "./types/tables";

interface Database {
  players: Player[];
  tables: Table[];
}

// A temporary in-memory DB for testing
const db: Database = {
  players: [
    { id: 1, username: "kgawkroge0", elo: 1799, table: 1 },
    { id: 2, username: "aoloinn1", elo: 1572, table: 2 },
    { id: 3, username: "cpandya2", elo: 1788, table: 3 },
    { id: 4, username: "aolyet3", elo: 1234, table: 4 },
    { id: 5, username: "holdknow4", elo: 1945, table: 5 },
    { id: 6, username: "awestoll5", elo: 1921 },
    { id: 7, username: "dhallgalley6", elo: 2022, table: 1 },
    { id: 8, username: "rasee7", elo: 698, table: 2 },
    { id: 9, username: "eandriuzzi8", elo: 2008, table: 3 },
    { id: 10, username: "vseid9", elo: 690, table: 4 },
    { id: 11, username: "wsprossona", elo: 2462, table: 5 },
    { id: 12, username: "slehrmannb", elo: 756 },
    { id: 13, username: "zglindec", elo: 2098, table: 1 },
    { id: 14, username: "edissmand", elo: 1605, table: 2 },
    { id: 15, username: "mivashove", elo: 2021, table: 3 },
    { id: 16, username: "afletcherf", elo: 631, table: 4 },
    { id: 17, username: "kbussg", elo: 959, table: 5 },
    { id: 18, username: "gconrarth", elo: 692 },
    { id: 19, username: "mbencheri", elo: 1274, table: 1 },
    { id: 20, username: "fvenusj", elo: 2230, table: 2 },
    { id: 21, username: "aoxenburyk", elo: 685, table: 3 },
    { id: 22, username: "amclayl", elo: 1581, table: 4 },
    { id: 23, username: "alansdownm", elo: 1597, table: 5 },
    { id: 24, username: "gbalstonn", elo: 1278 },
    { id: 25, username: "nsheddeno", elo: 590, table: 1 },
    { id: 26, username: "lhallowesp", elo: 1776, table: 2 },
    { id: 27, username: "mrakeq", elo: 1206, table: 3 },
    { id: 28, username: "noxenhamr", elo: 1044, table: 4 },
    { id: 29, username: "mdufaurs", elo: 1605, table: 5 },
    { id: 30, username: "twottont", elo: 1740 },
    { id: 31, username: "ggandersu", elo: 1127, table: 1 },
    { id: 32, username: "ggravestonev", elo: 677, table: 2 },
    { id: 33, username: "ewelchmanw", elo: 1424, table: 3 },
    { id: 34, username: "llefebrex", elo: 2251, table: 4 },
    { id: 35, username: "amerrimany", elo: 1369, table: 5 },
    { id: 36, username: "vhugillz", elo: 505 },
    { id: 37, username: "mswett10", elo: 545, table: 1 },
    { id: 38, username: "nlouca11", elo: 2395, table: 2 },
    { id: 39, username: "cthirkettle12", elo: 1569, table: 3 },
    { id: 40, username: "akinder13", elo: 1867, table: 4 },
    { id: 41, username: "abrimmicombe14", elo: 810, table: 5 },
    { id: 42, username: "swarcop15", elo: 1708 },
    { id: 43, username: "nreucastle16", elo: 2277, table: 1 },
    { id: 44, username: "hflack17", elo: 2094, table: 2 },
    { id: 45, username: "hbroggetti18", elo: 824, table: 3 },
    { id: 46, username: "rwaldram19", elo: 1125, table: 4 },
    { id: 47, username: "mmcgillreich1a", elo: 967, table: 5 },
    { id: 48, username: "gdulin1b", elo: 547 },
    { id: 49, username: "crozycki1c", elo: 1896, table: 1 },
    { id: 50, username: "banselmi1d", elo: 1960, table: 2 },
  ],
  tables: [
    {
      id: 1,
      tableOverview: {
        name: "Plajo",
        startingStack: 792,
        startingSB: 2,
        startingBB: 3,
        startingST: 20,
        decisionTime: 5,
        rotationsUntilBlindsIncrease: 4,
        blindIncreaseRatio: 1.49,
        variant: PokerVariants.NLH,
        maxPlayers: 10,
      },
      currentSB: 2,
      currentBB: 7,
      currentST: 9,
      hand: 38,
      option: 6,
      flop: [
        { value: Value.ACE, suit: Suit.HEART },
        { value: Value.TWO, suit: Suit.SPADE },
        { value: Value.KING, suit: Suit.HEART },
      ],
      turn: { value: Value.KING, suit: Suit.CLUB },
      river: { value: Value.EIGHT, suit: Suit.DIAMOND },
      seatingArrangement: [
        {
          tableID: 1,
          playerID: 1,
          stack: 2105,
          holeCards: [
            { value: Value.ACE, suit: Suit.SPADE },
            { value: Value.ACE, suit: Suit.DIAMOND },
          ],
          bettingHistory: [
            { action: BetActionType.SB, amount: 2 },
            { action: BetActionType.RAISE, amount: 500 },
            { action: BetActionType.BET, amount: 1000 },
            { action: BetActionType.CHECK },
            { action: BetActionType.ALL_IN_CALL, amount: 603 },
          ],
        },
        {
          tableID: 1,
          playerID: 7,
          stack: 1646,
          holeCards: [
            { value: Value.TEN, suit: Suit.SPADE },
            { value: Value.FOUR, suit: Suit.DIAMOND },
          ],
          bettingHistory: [
            { action: BetActionType.BB, amount: 7 },
            { action: BetActionType.FOLD },
          ],
        },
        {
          tableID: 1,
          playerID: 13,
          stack: 3706,
          holeCards: [
            { value: Value.KING, suit: Suit.DIAMOND },
            { value: Value.TEN, suit: Suit.DIAMOND },
          ],
          bettingHistory: [
            { action: BetActionType.ST, amount: 9 },
            { action: BetActionType.CALL, amount: 500 },
            { action: BetActionType.CALL, amount: 1000 },
            { action: BetActionType.BET, amount: 500 },
            { action: BetActionType.ALL_IN_CALL, amount: 1697 },
          ],
        },
        {
          tableID: 1,
          playerID: 19,
          stack: 4714,
          holeCards: [
            { value: Value.TWO, suit: Suit.CLUB },
            { value: Value.TWO, suit: Suit.HEART },
          ],
          bettingHistory: [
            { action: BetActionType.CALL, amount: 9 },
            { action: BetActionType.CALL, amount: 500 },
            { action: BetActionType.CALL, amount: 1000 },
            { action: BetActionType.ALL_IN_RAISE, amount: 3205 },
          ],
        },
        {
          tableID: 1,
          playerID: 25,
          stack: 36,
          holeCards: [
            { value: Value.FIVE, suit: Suit.SPADE },
            { value: Value.FIVE, suit: Suit.CLUB },
          ],
          bettingHistory: [{ action: BetActionType.ALL_IN_RAISE, amount: 36 }],
        },
        {
          tableID: 1,
          playerID: 31,
          stack: 2917,
          holeCards: [
            { value: Value.SIX, suit: Suit.SPADE },
            { value: Value.SIX, suit: Suit.CLUB },
          ],
          bettingHistory: [
            { action: BetActionType.RAISE, amount: 100 },
            { action: BetActionType.FOLD },
          ],
        },
        {
          tableID: 1,
          playerID: 37,
          stack: 747,
          holeCards: [
            { value: Value.QUEEN, suit: Suit.DIAMOND },
            { value: Value.JACK, suit: Suit.DIAMOND },
          ],
          bettingHistory: [{ action: BetActionType.FOLD }],
        },
        {
          tableID: 1,
          playerID: 43,
          stack: 2449,
          holeCards: [
            { value: Value.THREE, suit: Suit.CLUB },
            { value: Value.FOUR, suit: Suit.CLUB },
          ],
          bettingHistory: [{ action: BetActionType.FOLD }],
        },
        {
          tableID: 1,
          playerID: 49,
          stack: 2332,
          holeCards: [
            { value: Value.SEVEN, suit: Suit.HEART },
            { value: Value.SEVEN, suit: Suit.DIAMOND },
          ],
          bettingHistory: [{ action: BetActionType.FOLD }],
        },
      ],
    },
    {
      id: 2,
      tableOverview: {
        name: "Jaxspan",
        startingStack: 775,
        startingSB: 3,
        startingBB: 6,
        startingST: 8,
        decisionTime: 9,
        rotationsUntilBlindsIncrease: 4,
        blindIncreaseRatio: 2.76,
        variant: PokerVariants.NLH,
        maxPlayers: 10,
      },
      currentSB: 1,
      currentBB: 4,
      currentST: 14,
      hand: 133,
      seatingArrangement: [
        {
          tableID: 2,
          playerID: 2,
          stack: 4710,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 2,
          playerID: 8,
          stack: 2921,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 2,
          playerID: 14,
          stack: 2292,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 2,
          playerID: 20,
          stack: 3693,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 2,
          playerID: 26,
          stack: 2232,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 2,
          playerID: 32,
          stack: 3472,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 2,
          playerID: 38,
          stack: 4922,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 2,
          playerID: 44,
          stack: 133,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 2,
          playerID: 50,
          stack: 4387,
          holeCards: null,
          bettingHistory: null,
        },
      ],
    },
    {
      id: 3,
      tableOverview: {
        name: "Thoughtbeat",
        startingStack: 335,
        startingSB: 2,
        startingBB: 3,
        startingST: 10,
        decisionTime: 8,
        rotationsUntilBlindsIncrease: 4,
        blindIncreaseRatio: 2.32,
        variant: PokerVariants.NLH,
        maxPlayers: 9,
      },
      currentSB: 1,
      currentBB: 4,
      currentST: 20,
      hand: 259,
      option: 5,
      flop: [
        { value: Value.ACE, suit: Suit.HEART },
        { value: Value.TWO, suit: Suit.SPADE },
        { value: Value.KING, suit: Suit.HEART },
      ],
      turn: { value: Value.ACE, suit: Suit.CLUB },
      seatingArrangement: [
        {
          tableID: 3,
          playerID: 3,
          stack: 4134,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 3,
          playerID: 9,
          stack: 1957,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 3,
          playerID: 15,
          stack: 1535,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 3,
          playerID: 21,
          stack: 2084,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 3,
          playerID: 27,
          stack: 2222,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 3,
          playerID: 33,
          stack: 4064,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 3,
          playerID: 39,
          stack: 110,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 3,
          playerID: 45,
          stack: 415,
          holeCards: null,
          bettingHistory: null,
        },
      ],
    },
    {
      id: 4,
      tableOverview: {
        name: "Twitterlist",
        startingStack: 208,
        startingSB: 3,
        startingBB: 5,
        startingST: 12,
        decisionTime: 6,
        rotationsUntilBlindsIncrease: 4,
        blindIncreaseRatio: 3.76,
        variant: PokerVariants.NLH,
        maxPlayers: 8,
      },
      currentSB: 1,
      currentBB: 6,
      currentST: 15,
      hand: 52,
      option: 6,
      flop: [
        { value: Value.ACE, suit: Suit.HEART },
        { value: Value.TWO, suit: Suit.SPADE },
        { value: Value.KING, suit: Suit.HEART },
      ],
      turn: { value: Value.ACE, suit: Suit.CLUB },
      river: { value: Value.ACE, suit: Suit.DIAMOND },
      seatingArrangement: [
        {
          tableID: 4,
          playerID: 4,
          stack: 4475,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 4,
          playerID: 10,
          stack: 4120,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 4,
          playerID: 16,
          stack: 1326,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 4,
          playerID: 22,
          stack: 3931,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 4,
          playerID: 28,
          stack: 3738,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 4,
          playerID: 34,
          stack: 1244,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 4,
          playerID: 40,
          stack: 2688,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 4,
          playerID: 46,
          stack: 1970,
          holeCards: null,
          bettingHistory: null,
        },
      ],
    },
    {
      id: 5,
      tableOverview: {
        name: "PLOLOL",
        startingStack: 374,
        startingSB: 2,
        startingBB: 3,
        startingST: 12,
        decisionTime: 4,
        rotationsUntilBlindsIncrease: 5,
        blindIncreaseRatio: 1.68,
        variant: PokerVariants.PLO,
        maxPlayers: 8,
      },
      currentSB: 3,
      currentBB: 6,
      currentST: 12,
      hand: 382,
      option: 4,
      flop: [
        { value: Value.ACE, suit: Suit.HEART },
        { value: Value.TWO, suit: Suit.SPADE },
        { value: Value.KING, suit: Suit.HEART },
      ],
      seatingArrangement: [
        {
          tableID: 5,
          playerID: 5,
          stack: 1403,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 5,
          playerID: 11,
          stack: 1069,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 5,
          playerID: 17,
          stack: 1263,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 5,
          playerID: 23,
          stack: 360,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 5,
          playerID: 29,
          stack: 2570,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 5,
          playerID: 35,
          stack: 3166,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 5,
          playerID: 41,
          stack: 390,
          holeCards: null,
          bettingHistory: null,
        },
        {
          tableID: 5,
          playerID: 47,
          stack: 4315,
          holeCards: null,
          bettingHistory: null,
        },
      ],
    },
  ],
};
export default db;
